### ISSUE TITLE
Ask for sample code that shows how to get the face embedding

### ISSUE THREAD

**Issue by pcchen-kid** [sachith500/ContrastiveFaceRepresentation#2]
I am impressed by your research results and would like to use your trained model for some simple applications.

Suppose I've used some kind of face detection algorithm (such as MTCNN) to get cropped faces, I was wondering if you could provide a simple example code to illustrate how to get the face embedding (such as how to normalize the cropped face, etc.).

Thank you.

**Comment by sachith500** [comment]
Hi, I recommend grabbing the output of the encoder just after the encoder (at the end of the resnet). You may want to experiment with a few layers close to the end of the encoder for your particular application, though.

Hope this helps!
